version: '3.7'

volumes:
  mysql-data:

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=travel_ex
      - MYSQL_ROOT_PASSWORD=travel_test
      - MYSQL_USER=travel_test
      - MYSQL_PASSWORD=travel_test
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql