spring:
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data-h2.sql
      schema-locations: classpath:sql/schema-h2.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:travel;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
