spring:
  profiles:
    active: deployment

---
spring:
  config:
    activate:
      on-profile: deployment, test

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data-h2.sql
      schema-locations: classpath:sql/schema-h2.sql

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:travel;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: production

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data-mysql.sql
      schema-locations: classpath:sql/schema-mysql.sql

  datasource:
    url: jdbc:mysql://localhost:3306/travel_ex?serverTimezone=Asia/Seoul
    username: travel_test
    password: travel_test
    driver-class-name: com.mysql.cj.jdbc.Driver
