CREATE TABLE city (
    id bigint generated by default as identity,
    name varchar(255) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE member (
    id bigint generated by default as identity,
    name varchar(255) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE travel (
    id bigint generated by default as identity,
    city_id bigint NOT NULL,
    member_id bigint NOT NULL,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE city_view_history (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    city_id bigint not null,
    member_id bigint not null,
    PRIMARY KEY (id)
);

ALTER TABLE travel ADD CONSTRAINT FK_TRAVEL_CITY_ID FOREIGN KEY (city_id) REFERENCES city;
ALTER TABLE travel ADD CONSTRAINT FK_TRAVEL_MEMBER_ID FOREIGN KEY (member_id) REFERENCES member;
ALTER TABLE city_view_history ADD CONSTRAINT FK_CITY_VIEW_HISTORY_CITY_ID FOREIGN KEY (city_id) REFERENCES city;
ALTER TABLE city_view_history ADD CONSTRAINT FK_CITY_VIEW_HISTORY_MEMBER_ID FOREIGN KEY (member_id) REFERENCES member;