CREATE TABLE city (
    id bigint generated by default as identity,
    name varchar(255) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE member (
    id bigint generated by default as identity,
    name varchar(255) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE travel (
    id bigint generated by default as identity,
    city_id bigint NOT NULL,
    member_id bigint NOT NULL,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    PRIMARY KEY (id)
);

ALTER TABLE travel ADD CONSTRAINT travel_city_fk_id FOREIGN KEY (city_id) REFERENCES city;
ALTER TABLE travel ADD CONSTRAINT travel_member_fk_id FOREIGN KEY (member_id) REFERENCES member;